name: mobicash
description: Controle de gastos pessoais
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  intl: ^0.18.1
  fl_chart: ^1.0.0
  flutter_multi_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/iconApp.png
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/iconApp.png
